# Site settings
title: Mika's Clojure
email: mika.turkia at helsinki.fi
description: Clojure-related writings. 
baseurl: "/clj"
url: "http://turkia.github.io"
github_username: turkia

# Build settings
markdown: kramdown
